stages:
  extract_dwight:
    matrix:
      date: ['2025-01-01', '2025-01-07']
      block: [reward-type-medium-cst-rtt-dco, reward-type-medium-large-cst-rtt-dco,
        reward-type-choice]
    cmd: python scripts/extract_trial_frame.py ${raw_data_dir}/Dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat
      --out 
      data/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.parquet
      --block ${item.block} ${logging} ${extract}
    params:
    - extract
    - logging
    deps:
    - scripts/extract_trial_frame.py
    - src/
    - ${raw_data_dir}/Dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat
    - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
    outs:
    - data/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.parquet
    - ${logging.logdir}/extract/Dwight_${item.date}_${item.block}_tf.log
  extract_prez:
    matrix:
      date: ['2022-07-21']
      block: [cst-rtt]
    cmd: python scripts/extract_trial_frame.py ${raw_data_dir}/Prez/${item.date}/Prez_${item.date}_${item.block}_sorted.mat
      --out 
      data/trialframe/Prez/${item.date}/blocks/Prez_${item.date}_${item.block}_tf.parquet
      --block ${item.block} ${logging} ${extract}
    params:
    - extract
    - logging
    deps:
    - scripts/extract_trial_frame.py
    - src/
    - ${raw_data_dir}/Prez/${item.date}/Prez_${item.date}_${item.block}_sorted.mat
    - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
    outs:
    - data/trialframe/Prez/${item.date}/blocks/Prez_${item.date}_${item.block}_tf.parquet
    - ${logging.logdir}/extract/Prez_${item.date}_${item.block}_tf.log
  combine_session:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/combine_session.py data/trialframe/${item.monkey}/${item.date}/blocks/
        --out 
        data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        ${logging}
      params:
      - logging
      deps:
      - scripts/combine_session.py
      - src/
      - data/trialframe/${item.monkey}/${item.date}/blocks/
      outs:
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      - ${logging.logdir}/combine/${item.monkey}_${item.date}_tf.log
  context_axis:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/get_context_axis.py 
        data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        --out 
        results/context_axis/${item.monkey}/${item.date}/${item.monkey}_${item.date}_context_axis.svg
        ${logging}
      params:
      - logging
      deps:
      - scripts/get_context_axis.py
      - src/
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      outs:
      - ${logging.logdir}/context_axis/${item.monkey}_${item.date}_context_axis.log
      plots:
      - results/context_axis/${item.monkey}/${item.date}/${item.monkey}_${item.date}_context_axis.svg
  cross_task_decoding:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/cross_task_decoding.py 
        data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        --out results/cross-task-decoding/${item.monkey}/${item.date}/ ${logging}
      params:
      - logging
      deps:
      - scripts/cross_task_decoding.py
      - src/
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      outs:
      - ${logging.logdir}/cross-task-decoding/${item.monkey}_${item.date}_cross-task-decoding.log
      plots:
      - results/cross-task-decoding/${item.monkey}/${item.date}/${item.monkey}_${item.date}_decoder-task-score-heatmap.svg
      - results/cross-task-decoding/${item.monkey}/${item.date}/${item.monkey}_${item.date}_decoder-trial-scores-scatter.svg
      - results/cross-task-decoding/${item.monkey}/${item.date}/trials/
  prep_lfads_tensors:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/prep_lfads_tensors.py 
        data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        --out data/pre-lfads-tensors/${item.monkey}_${item.date}_tensors.hdf5
        --info_path conf/lfads/dataset_info/${item.monkey}_${item.date}.yaml
        ${logging} ${prep_lfads_tensors}
      params:
      - prep_lfads_tensors
      - logging
      deps:
      - scripts/prep_lfads_tensors.py
      - src/
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      outs:
      - data/pre-lfads-tensors/${item.monkey}_${item.date}_tensors.hdf5
      - ${logging.logdir}/prep-lfads-tensors/${item.monkey}_${item.date}_tensors.log
  train_lfads:
    foreach: ${lfads_sessions}
    do:
      cmd: python scripts/train_lfads.py
        --dataset '${item.monkey}_${item.date}'
        ${logging} ${train_lfads}
      params:
      - train_lfads
      - logging
      deps:
      - scripts/train_lfads.py
      - src/
      - data/pre-lfads-tensors/${item.monkey}_${item.date}_tensors.hdf5
      - conf/lfads/
      outs:
      - ${logging.logdir}/train-lfads/${item.monkey}_${item.date}.log
      - results/lfads/${item.monkey}_${item.date}/lightning_checkpoints
      - results/lfads/${item.monkey}_${item.date}/dvclive
      - results/lfads/${item.monkey}_${item.date}/lfads_model.pt
      - results/lfads/${item.monkey}_${item.date}/lfads_output_${item.monkey}_${item.date}_tensors.h5