stages:
  extract:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/extract_normalized_data.py --dataset ${item.monkey}_${item.date} ${dir_structure} ${logging} ${extract}
      params:
      - extract
      - logging
      - dir_structure
      deps:
      - scripts/extract_normalized_data.py
      - ${dir_structure.raw_data_dir}/${item.monkey}/${item.date}/
      - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
      outs:
      - ${dir_structure.trialframe_dir}/${item.monkey}_${item.date}/${item.monkey}_${item.date}_meta.parquet
      - ${dir_structure.trialframe_dir}/${item.monkey}_${item.date}/${item.monkey}_${item.date}_states.parquet
      - ${dir_structure.trialframe_dir}/${item.monkey}_${item.date}/${item.monkey}_${item.date}_hand-pos.parquet
      - ${dir_structure.trialframe_dir}/${item.monkey}_${item.date}/${item.monkey}_${item.date}_neural-spikes-binned.parquet
      - ${dir_structure.log_dir}/extract/${item.monkey}_${item.date}.log
#   extract_trialframes:
#     foreach: ${monkey_sessions}
#     do:
#       cmd: python scripts/extract_trial_frame.py --dataset ${item.monkey}_${item.date} ${dir_structure} ${logging} ${extract}
#       params:
#       - extract
#       - logging
#       - dir_structure
#       deps:
#       - scripts/extract_trial_frame.py
#       - ${raw_data_dir}/Dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat
#       - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
#       outs:
#       - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
#       - ${dir_structure.log_dir}/extract/${item.monkey}_${item.date}_tf.log
  prep_lfads_tensors:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/prep_lfads_tensors.py 
        data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        --out data/pre-lfads-tensors/${item.monkey}_${item.date}_tensors.hdf5
        --info_path conf/lfads/dataset_info/${item.monkey}_${item.date}.yaml
        ${logging} ${prep_lfads_tensors} ${dir_structure}
      params:
      - prep_lfads_tensors
      - logging
      deps:
      - scripts/prep_lfads_tensors.py
      - src/munge.py
      - src/chop_merge.py
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      outs:
      - data/pre-lfads-tensors/${item.monkey}_${item.date}_tensors.hdf5
      - ${dir_structure.log_dir}/prep-lfads-tensors/${item.monkey}_${item.date}_tensors.log
  train_lfads:
    foreach: ${lfads_sessions}
    do:
      frozen: true
      cmd: python scripts/train_lfads.py
        --dataset '${item.monkey}_${item.date}'
        ${logging} ${train_lfads} ${dir_structure}
      params:
      - train_lfads
      - logging
      deps:
      - scripts/train_lfads.py
      - src/lfads_dvc.py
      - src/lfads_callbacks.py
      - data/pre-lfads-tensors/${item.monkey}_${item.date}_tensors.hdf5
      - conf/lfads/
      outs:
      - ${dir_structure.log_dir}/train-lfads/${item.monkey}_${item.date}.log
      - results/lfads/${item.monkey}_${item.date}/lightning_checkpoints
      - results/lfads/${item.monkey}_${item.date}/dvclive
      - results/lfads/${item.monkey}_${item.date}/lfads_model.pt
      - results/lfads/${item.monkey}_${item.date}/lfads_output_${item.monkey}_${item.date}_tensors.h5
  merge_lfads_outputs:
    foreach: ${lfads_sessions}
    do:
      cmd: python scripts/merge_lfads_outputs.py --dataset ${item.monkey}_${item.date} --overlap ${prep_lfads_tensors.overlap} ${dir_structure} ${logging}
      params:
      - dir_structure
      - logging
      - prep_lfads_tensors.overlap
      deps:
      - scripts/merge_lfads_outputs.py
      - src/chop_merge.py
      - src/munge.py
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      - results/lfads/${item.monkey}_${item.date}/lfads_output_${item.monkey}_${item.date}_tensors.h5
      outs:
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_neural-lfads-rates.parquet
      - ${dir_structure.log_dir}/merge-lfads-outputs/${item.monkey}_${item.date}.log
  context_axis:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/get_context_axis.py 
        data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        --out 
        results/context_axis/${item.monkey}/${item.date}/${item.monkey}_${item.date}_context_axis.svg
        ${dir_structure} ${logging}
      params:
      - logging
      deps:
      - scripts/get_context_axis.py
      - src/
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      outs:
      - ${dir_structure.log_dir}/context_axis/${item.monkey}_${item.date}_context_axis.log
      plots:
      - results/context_axis/${item.monkey}/${item.date}/${item.monkey}_${item.date}_context_axis.svg
  cross_task_decoding:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/cross_task_decoding.py 
        data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        --out results/cross-task-decoding/${item.monkey}/${item.date}/ ${logging} ${dir_structure}
      params:
      - logging
      deps:
      - scripts/cross_task_decoding.py
      - src/
      - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      outs:
      - ${dir_structure.log_dir}/cross-task-decoding/${item.monkey}_${item.date}_cross-task-decoding.log
      plots:
      - results/cross-task-decoding/${item.monkey}/${item.date}/${item.monkey}_${item.date}_decoder-task-score-heatmap.svg
      - results/cross-task-decoding/${item.monkey}/${item.date}/${item.monkey}_${item.date}_decoder-trial-scores-scatter.svg
      - results/cross-task-decoding/${item.monkey}/${item.date}/trials/