stages:
  extract_dwight:
    matrix:
      date: ['2025-01-01','2025-01-07']
      block: ['reward-type-medium-cst-rtt-dco', 'reward-type-medium-large-cst-rtt-dco', 'reward-type-choice']
    cmd: python scripts/extract_trial_frame.py ${raw_data_dir}/Dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat --out data/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.parquet --block ${item.block} ${extract}
    params:
      - extract
    deps:
      - scripts/extract_trial_frame.py
      - ${raw_data_dir}/Dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat
      - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
    outs:
      - data/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.parquet
      - data/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.log
  extract_prez:
    matrix:
      date: ['2022-07-21']
      block: ['cst-rtt']
    cmd: python scripts/extract_trial_frame.py ${raw_data_dir}/Prez/${item.date}/Prez_${item.date}_${item.block}_sorted.mat --out data/trialframe/Prez/${item.date}/blocks/Prez_${item.date}_${item.block}_tf.parquet --block ${item.block} ${extract}
    params:
      - extract
    deps:
      - scripts/extract_trial_frame.py
      - ${raw_data_dir}/Prez/${item.date}/Prez_${item.date}_${item.block}_sorted.mat
      - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
    outs:
      - data/trialframe/Prez/${item.date}/blocks/Prez_${item.date}_${item.block}_tf.parquet
      - data/trialframe/Prez/${item.date}/blocks/Prez_${item.date}_${item.block}_tf.log
  combine_session:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/combine_session.py data/trialframe/${item.monkey}/${item.date}/blocks/ --out data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet ${combine_session}
      params:
        - combine_session
      deps:
        - scripts/combine_session.py
        - data/trialframe/${item.monkey}/${item.date}/blocks/
      outs:
        - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
        - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.log
  context_axis:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/get_context_axis.py data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet --out results/context_axis/${item.monkey}/${item.date}/${item.monkey}_${item.date}_context_axis.svg ${context_axis}
      params:
        - context_axis
      deps:
        - scripts/get_context_axis.py
        - data/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.parquet
      outs:
        - results/context_axis/${item.monkey}/${item.date}/${item.monkey}_${item.date}_context_axis.svg
        - results/context_axis/${item.monkey}/${item.date}/${item.monkey}_${item.date}_context_axis.log