vars:
  - params.yaml
  - conf/trialframe.yaml
  - conf/lfads/lfads-torch.yaml

stages:
  extract:
    foreach: ${datasets}
    do:
      cmd: python scripts/extract_normalized_data.py --dataset ${item.dataset_name} ${dir_structure} ${logging} ${extract}
      params:
      - extract
      - logging
      - dir_structure
      deps:
      - scripts/extract_normalized_data.py
      - ${dir_structure.raw_data_dir}/${item.monkey}/${item.date}/
      - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
      outs:
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_meta.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_states.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_hand-pos.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_neural-spikes-binned.parquet
      - ${dir_structure.log_dir}/extract/${item.dataset_name}.log
  smooth_firing_rates:
    foreach: ${datasets}
    do:
      cmd: python scripts/smooth_firing_rates.py --dataset ${item.dataset_name} ${dir_structure} ${logging} ${smooth_firing_rates}
      params:
      - logging
      - dir_structure
      - smooth_firing_rates
      deps:
      - scripts/smooth_firing_rates.py
      - src/munge.py
      - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract/smoothing.py
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_neural-spikes-binned.parquet
      outs:
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_neural-smooth-rates.parquet
      - ${dir_structure.log_dir}/smooth-firing-rates/${item.dataset_name}.log
  prep_lfads_tensors:
    foreach: ${datasets}
    do:
      cmd: python scripts/prep_lfads_tensors.py 
        ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_neural-spikes-binned.parquet
        --out ${dir_structure.pre-lfads_dir}/${item.dataset_name}_tensors.hdf5
        --info_path ${dir_structure.config_dir}/lfads/dataset_info/${item.dataset_name}.yaml
        ${logging} ${prep_lfads_tensors} ${dir_structure}
      params:
      - prep_lfads_tensors
      - logging
      - dir_structure
      deps:
      - scripts/prep_lfads_tensors.py
      - src/munge.py
      - src/chop_merge.py
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_neural-spikes-binned.parquet
      outs:
      - ${dir_structure.pre-lfads_dir}/${item.dataset_name}_tensors.hdf5
      - ${dir_structure.log_dir}/prep-lfads-tensors/${item.dataset_name}_tensors.log
  train_lfads:
    foreach: ${datasets}
    do:
      frozen: true
      cmd: python scripts/train_lfads.py
        --dataset ${item.dataset_name}
        --config ../${dir_structure.config_dir}/lfads/lfads-torch.yaml
        ${logging} ${dir_structure}
      params:
      - logging
      - dir_structure
      - conf/lfads/lfads-torch.yaml:
      - conf/lfads/dataset_info/${item.dataset_name}.yaml:
      - conf/lfads/callbacks/plots.yaml:
      - conf/lfads/datamodule/single_session_datamodule.yaml:
      - conf/lfads/model/single_session_model.yaml:
      deps:
      - scripts/train_lfads.py
      - src/lfads_dvc.py
      - src/lfads_callbacks.py
      - ${dir_structure.pre-lfads_dir}/${item.dataset_name}_tensors.hdf5
      - ${dir_structure.config_dir}/lfads
      outs:
      - ${dir_structure.log_dir}/train-lfads/${item.dataset_name}.log
      - ${dir_structure.results_dir}/lfads/${item.dataset_name}/lightning_checkpoints:
          persist: false
      - ${dir_structure.results_dir}/lfads/${item.dataset_name}/dvclive
      - ${dir_structure.results_dir}/lfads/${item.dataset_name}/lfads_model.pt
      - ${dir_structure.results_dir}/lfads/${item.dataset_name}/lfads_output_${item.dataset_name}_tensors.h5
  merge_lfads_outputs:
    foreach: ${datasets}
    do:
      cmd: python scripts/merge_lfads_outputs.py --dataset ${item.dataset_name} --overlap ${prep_lfads_tensors.overlap} ${dir_structure} ${logging}
      params:
      - dir_structure
      - logging
      - prep_lfads_tensors.overlap
      deps:
      - scripts/merge_lfads_outputs.py
      - src/chop_merge.py
      - src/munge.py
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_neural-spikes-binned.parquet
      - ${dir_structure.results_dir}/lfads/${item.dataset_name}/lfads_output_${item.dataset_name}_tensors.h5
      outs:
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_neural-lfads-rates.parquet
      - ${dir_structure.log_dir}/merge-lfads-outputs/${item.dataset_name}.log
  context_axis:
    foreach: ${datasets}
    do:
      cmd: python scripts/get_context_axis.py --dataset ${item.dataset_name} 
        --composition_config ${dir_structure.config_dir}/trialframe.yaml
        ${dir_structure} ${logging}
      params:
      - logging
      - dir_structure
      - conf/trialframe.yaml:
      deps:
      - scripts/get_context_axis.py
      - src/munge.py
      - src/cli.py
      - src/crystal_models.py
      - src/time_slice.py
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${info}.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${composition.state}.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${composition.hand position}.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${composition.motor cortex}.parquet
      outs:
      - ${dir_structure.log_dir}/context_axis/${item.dataset_name}.log
      plots:
      - ${dir_structure.results_dir}/context_axis/${item.dataset_name}_context_axis.svg
  cross_task_decoding:
    foreach: ${datasets}
    do:
      cmd: python scripts/cross_task_decoding.py --dataset ${item.dataset_name} 
        --composition_config ${dir_structure.config_dir}/trialframe.yaml
        ${dir_structure} ${logging}
      params:
      - logging
      - dir_structure
      - conf/trialframe.yaml:
      deps:
      - scripts/cross_task_decoding.py
      - src/munge.py
      - src/cli.py
      - src/crystal_models.py
      - src/time_slice.py
      - src/timeseries.py
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${info}.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${composition.state}.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${composition.hand position}.parquet
      - ${dir_structure.trialframe_dir}/${item.dataset_name}/${item.dataset_name}_${composition.motor cortex}.parquet
      outs:
      - ${dir_structure.log_dir}/cross-task-decoding/${item.dataset_name}.log
      plots:
      - results/cross-task-decoding/${item.dataset_name}/${item.dataset_name}_decoder-task-score-heatmap.svg
      - results/cross-task-decoding/${item.dataset_name}/${item.dataset_name}_decoder-trial-scores-scatter.svg
      - results/cross-task-decoding/${item.dataset_name}/trial-predictions/