stages:
  extract_dwight:
    matrix:
      date: ['2025-01-07']
      block: ['reward-type_medium_cst-rtt-dco', 'reward-type_medium-large_cst-rtt-dco', 'reward-type-choice']
    cmd: python scripts/extract_trial_frame.py data/dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat --out results/dwight/${item.date}/Dwight_${item.date}_${item.block}_tf.pkl --block ${item.block} ${extract}
    params:
      - extract
    deps:
      - scripts/extract_trial_frame.py
      - data/dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat
      - /home/codebase/0-projects/smile-extraction/
    outs:
      - results/dwight/${item.date}/Dwight_${item.date}_${item.block}_tf.pkl
      - results/dwight/${item.date}/Dwight_${item.date}_${item.block}_tf.log