stages:
  extract_dwight:
    matrix:
      date: ['2025-01-07']
      block: ['reward-type-medium-cst-rtt-dco', 'reward-type-medium-large-cst-rtt-dco', 'reward-type-choice']
    cmd: python scripts/extract_trial_frame.py data/dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat --out results/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.pkl --block ${item.block} ${extract}
    params:
      - extract
    deps:
      - scripts/extract_trial_frame.py
      - data/dwight/${item.date}/Dwight_${item.date}_${item.block}_sorted.mat
      - /Users/raeed/codebase/0-projects/smile-extraction/smile_extract
    outs:
      - results/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.pkl
      - results/trialframe/Dwight/${item.date}/blocks/Dwight_${item.date}_${item.block}_tf.log
  combine_session:
    foreach: ${monkey_sessions}
    do:
      cmd: python scripts/combine_session.py results/trialframe/${item.monkey}/${item.date}/blocks/ --out results/trialframe/${item.monkey}/${item.date}/${item.monkey}_${item.date}_tf.pkl ${combine_session}
      params:
        - combine_session
      deps:
        - scripts/combine_session.py
        - results/trialframe/${item.monkey}/${item.date}/blocks/
      outs:
        - results/trialframe/${item.monkey}/${item.date}/Dwight_${item.date}_tf.pkl
        - results/trialframe/${item.monkey}/${item.date}/Dwight_${item.date}_tf.log
  # extract_prez:
    # date: ['2022-07-21']
  # context_axis:
  #   foreach:
  #     - date: '2025-01-07'
  #   do:
  #     cmd: python scripts/get_context_axis.py results/dwight/${item.date}/Dwight_${item.date}_tf.pkl --out results/dwight/${item.date}/Dwight_${item.date}_context_axis.pkl ${context_axis}