raw_data_dir: '/Users/raeed/Library/CloudStorage/OneDrive-UniversityofPittsburgh/0-projects/cst-rtt/cst-data/smile_format'
monkey_sessions:
  - monkey: 'Prez'
    date: '2022-07-21'
  - monkey: 'Dwight'
    date: '2025-01-01'
  - monkey: 'Dwight'
    date: '2025-01-07'
extract:
  bin_size: '10ms'
  min_firing_rate: 0.1
  max_spike_coincidence: 0.2
  rate_artifact_threshold: 350
  verbose: True
combine_session:
  verbose: True
context_axis:
  verbose: True
cross_task_decoding:
  verbose: True