raw_data_dir: '/Users/raeed/Library/CloudStorage/OneDrive-UniversityofPittsburgh/0-projects/cst-rtt/cst-data/preTD'
monkey_sessions:
  - monkey: 'Dwight'
    date: '2025-01-07'
    blocks:
      - reward-type-medium-cst-rtt-dco
      - reward-type-medium-large-cst-rtt-dco
      - reward-type-choice
extract:
  bin_size: '10ms'
  min_firing_rate: 0.1
  max_spike_coincidence: 0.2
  verbose: True
combine_session:
  verbose: True
context_axis:
  verbose: True