defaults:
  - dataset_info: Prez_2022-07-21
  - datamodule: single_session_datamodule
  - model: single_session_model
  - callbacks: plots
  - _self_

seed: 0
ignore_warnings: False

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: "auto"
  gradient_clip_val: 200
  max_epochs: 1_000 #
  log_every_n_steps: 5

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: valid/recon_smth
    mode: min
    save_top_k: 1
    save_last: True
    verbose: False
    dirpath: lightning_checkpoints
    auto_insert_metric_name: False
  early_stopping:
    _target_: lfads_torch.extensions.tune.EarlyStoppingWithBurnInPeriod
    monitor: valid/recon_smth
    mode: min
    patience: 10 #
    min_delta: 0
    burn_in_period: ${max:${sum:${model.l2_start_epoch},${model.l2_increase_epoch}},${sum:${model.kl_start_epoch},${model.kl_increase_epoch}}}
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch

logger:
  dvclive_logger:
    _target_: src.lfads_dvc.DVCLiveLFADSLogger
    save_dvc_exp: False
    log_model: False

posterior_sampling:
  use_best_ckpt: True
  fn:
    _target_: lfads_torch.post_run.analysis.run_posterior_sampling
    filename: lfads_output.h5
    num_samples: 50
