defaults:
  - datamodule: Prez_2022-07-21_cst-rtt
  - model: Prez_2022-07-21_cst-rtt

seed: 0
ignore_warnings: False

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: "mps"
  devices: 1
  gradient_clip_val: 200
  max_epochs: 100 #
  log_every_n_steps: 5

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: valid/recon_smth
    mode: min
    save_top_k: 1
    save_last: True
    verbose: False
    dirpath: lightning_checkpoints
    auto_insert_metric_name: False
  early_stopping:
    _target_: lfads_torch.extensions.tune.EarlyStoppingWithBurnInPeriod
    monitor: valid/recon_smth
    mode: min
    patience: 10 #
    min_delta: 0
    burn_in_period: ${max:${sum:${lfads.model.l2_start_epoch},${lfads.model.l2_increase_epoch}},${sum:${lfads.model.kl_start_epoch},${lfads.model.kl_increase_epoch}}}
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch

logger:
  csv_logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: "csv_logs"
    version: ""
    name: ""
  tensorboard_logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: "."
    version: ""
    name: ""

posterior_sampling:
  use_best_ckpt: True
  fn:
    _target_: lfads_torch.post_run.analysis.run_posterior_sampling
    filename: lfads_output.h5
    num_samples: 50
