_target_: lfads_torch.datamodules.BasicDataModule
datafile_pattern: ${relpath:data/pre-lfads-tensors/Prez_2022-07-21_cst-rtt_tensors.hdf5}
batch_keys:
  - behavior
attr_keys:
  - psth
  - train_cond_idx
  - valid_cond_idx
  - train_decode_mask
  - valid_decode_mask
batch_size: 250