_target_: lfads_torch.datamodules.BasicDataModule
datafile_pattern: ${relpath:data/pre-lfads-tensors/${dataset_info.dataset_name}}
batch_keys: []
attr_keys:
  - train_trial_id
  - train_chop_id
  - valid_trial_id
  - valid_chop_id
batch_size: 250