name: tests

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install \
            pytest pytest-cov \
            numpy pandas scipy scikit-learn xarray pyarrow omegaconf

      - name: Run pytest
        env:
          MPLBACKEND: Agg
        run: |
          pytest
